### ISSUE TITLE
How would one extract the uptime

### ISSUE THREAD

**Issue by fliiiix** [kepsic/routeros_telegraf_exporter#1]
* RouterOS to Telegraf metrics exporter version: 0.1.13
* Python version: Python 3.8.6
* Operating System: Fedora release 32 (Thirty Two)

### Description

I'm trying to extract the `uptime` of the RouterOS.

### What I Did

My `hosts_config.yaml` looks like this: 

```
- default:
      resources:
#          - path: /system/resource
#            interval: 30
#            tags:
#                  - board-name
#                  - disabled
#            values:
#                  - cpu-load
          - path: /system/resource
            interval: 15
            tags:
                  - board-name
                  - disabled
            values:
                  - uptime
- hostname.domain.network:
      resources:
```

I would expect to get the the uptime with `rte --hosts-config-file hosts_config.yaml -i` but it returns nothing.
